[[watch]]
# What the command does?
name = "print hello"
# Where to look for changes?
path = "src"
# What to execute on change?
command = "echo \"hello $EVENT_PATH\""

# Repeat this to watch multiple paths
